/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 source/sample.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Astronaut (props) {
  const { nodes, materials } = useGLTF('/models/source/sample.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geometry_0.geometry} material={nodes.geometry_0.material} />
    </group>
  )
}

useGLTF.preload('/models/source/sample.glb')
