import type { Metadata } from "next";
import React from 'react'
import { ClerkProvider } from '@clerk/nextjs'

import "./globals.css";
import NavBar from '@/layouts/NavBar.jsx'
import Footer from '@/layouts/Footer.jsx'
import BG from '@/layouts/BG.jsx'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <NavBar />
        <BG />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
